_main_/urls.py
from django.contrib.staticfiles.urls import static

from django.contrib import admin
from django.urls import path, include, re_path
from _main_ import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("project/", include("project.urls", namespace="project")),
    path("api-auth/", include("rest_framework.urls")),
    path("api/", include("api.urls"), name="api"),
    path("", include("common.urls", namespace="common")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    if "debug_toolbar" in settings.INSTALLED_APPS:
        urlpatterns += [
            re_path(r"^__debug__/", include(debug_toolbar.urls)),
        ]

api/urls.py
from django.conf.urls import include
from rest_framework import routers
from django.urls import path
from api import views


router = routers.DefaultRouter()
router.register(
    "projectregister", views.ProjectRegisterViewSet, basename="projectregister"
)

urlpatterns = [
    path("", include((router.urls, "api"))),
]

common/urls.py
from django.urls import path
from .views import Accueil


app_name = "common"

urlpatterns = [
    path("accueil/", Accueil.as_view(), {"pk": None}, name="accueil"),
    path("user/<int:pk>/", Accueil.as_view(), name="user-detail"),
    path("", Accueil.as_view(), {"pk": None}),
]

project/urls.py
from django.urls import path
from .views import (
    ProjectList,
    ProjectDetail,
    ProjectAdminListView,
    ProjectAdminCreateView,
    ProjectRegisterUpdateView,
)

app_name = "project"

urlpatterns = [
    path("", ProjectList.as_view(), name="project-list"),
    path(
        "<int:pk>", ProjectDetail.as_view(), {"register": False}, name="project-detail"
    ),
    path(
        "register/<int:pk>",
        ProjectDetail.as_view(template_name="project/projectregister_detail.html"),
        {"register": True},
        name="project-register-detail",
    ),
    path(
        "register/update/<int:pk>",
        ProjectRegisterUpdateView.as_view(),
        name="project-register-update",
    ),
    path("admin/create", ProjectAdminCreateView.as_view(), name="project-create"),
    path("admin/", ProjectAdminListView.as_view(), name="project-tools"),
]

project/models/project.py
from django.db import models
from django.db.models import Count, Q
from django.urls import reverse
from django.utils import timezone
from common.manager import IntraCeQueryset


PROJECT_S = "project-resource/"
PROJECT_P = "project-pdf/"


class Project(models.Model):
    """
        models Projects
        one projects have many creator
    """

    name = models.CharField(max_length=50)
    description = models.TextField(null=True)
    creators = models.ManyToManyField("common.User")
    created = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=False)
    parent = models.ForeignKey(
        "project.Project", on_delete=models.SET_NULL, null=True, blank=True,
    )
    experience = models.PositiveIntegerField(default=50)
    corrector_number = models.PositiveSmallIntegerField(default=2)
    groups_number = models.PositiveSmallIntegerField(default=1)
    resource = models.FileField(
        upload_to=PROJECT_S, max_length=100, null=True, blank=True,
    )
    documentation = models.FileField(upload_to=PROJECT_P, max_length=100)
    videos = models.ManyToManyField("project.ProjectLink", blank=True)
    languages = models.ManyToManyField("project.ProgLang", blank=True)
    category = models.ManyToManyField("project.Category", blank=True)
    objectives = models.ManyToManyField("project.Objective", blank=True)
    skills = models.ManyToManyField("project.Skill", blank=True)
    objects = IntraCeQueryset.as_manager()

    def __str__(self):
        return self.name

    @property
    def is_group(self):
        return True if self.groups_number > 1 else False

    @classmethod
    def prefetch_std(cls):
        return ["creators", "videos", "languages", "category"]

    def get_absolute_url(self):
        return reverse("project:project-detail", kwargs={"pk": self.pk})

    def get_version(self):
        # aggregate version
        if hasattr(self, "ag_version"):
            return self.ag_version
        return self.projectversion_set.aggregate(Count("pk"))["pk"]

    def extra(self):
        extra = self.__class__.objects.aggregate(
            num=Count("projectregister__pk"),
            num_finish=Count(
                "projectregister__pk", filter=Q(projectregister__status="CLOSED")
            ),
            num_student=Count("projectregister__teams__pk")
            + Count("projectregister__leader__pk"),
            num_fail=Count(
                "projectregister__pk",
                filter=Q(
                    projectregister__status="FINISH", projectregister__scores__lt=70
                ),
            ),
            num_success=Count(
                "projectregister__pk",
                filter=Q(
                    projectregister__status="FINISH", projectregister__scores__gte=70
                ),
            ),
            num_notyet=Count(
                "projectregister__pk", filter=Q(projectregister__scores__isnull=True),
            ),
        )
        return extra

project/models/project_register.py
from django.db import models
from django.utils.translation import gettext as _
from common.manager import IntraCeQueryset
from django.utils import timezone
from django.db.models import Count, Max, Q
from django.urls import reverse


class ProjectRegister(models.Model):
    """
        models for project's user register
    """

    leader = models.ForeignKey(
        "common.User", on_delete=models.SET_NULL, related_name="leaders", null=True
    )
    teams = models.ManyToManyField("common.User", related_name="teams", blank=True)
    invitations = models.ManyToManyField(
        "common.User", related_name="invitations", blank=True
    )
    project = models.ForeignKey("project.Project", on_delete=models.CASCADE, null=False)

    """
        status qui gere le satus du project , 
        __WAIT = en attente de l'equipe ..ect
        __PROGRESS = en cours sur le project
        __FINISH = le project est clos , vous ne pouvez plus le modifier
    """
    __WAIT = "WAIT"
    __PROGRESS = "PROGRESS"
    __FINISH = "FINISH"
    __CORRECT = "CORRECTED"

    STATUS_CHOICES = (
        (__WAIT, _("En attente")),
        (__PROGRESS, _("En Cours")),
        (__FINISH, _("Terminer")),
    )
    status = models.CharField(
        max_length=8, choices=STATUS_CHOICES, default=__WAIT, blank=False
    )

    """
        date du debut et de fin du project
    """
    started = models.DateTimeField(auto_now_add=True, null=False)
    finished = models.DateTimeField(null=True, blank=True)

    git = models.URLField(max_length=200, blank=True, null=True)
    scores = models.IntegerField(blank=True, null=True, default=None)

    objects = IntraCeQueryset.as_manager()

    def __str__(self):
        return self.project.__str__()

    class Meta:
        ordering = ("-started",)

    @property
    def is_group(self):
        return self.project.is_group

    @classmethod
    def prefetch_std(cls):
        return ["user"]

    def start_or_end(self):
        return self.finished or self.started

    def get_absolute_url(self):
        return reverse(
            "project:project-register-detail", kwargs={"pk": self.project.pk}
        )

    @classmethod
    def finish(cls, user, project):
        obj = cls.objects.filter(leader=user, project=project, status=cls.__PROGRESS)
        count = obj.count()
        if count == 1:
            obj = obj.first()
            obj.finished = timezone.now()
            obj.status = cls.__FINISH
            obj.save()
            return obj
        raise ValueError(_("Vous ne pouvez pas terminer ce project"))

    @classmethod
    def close(cls, user, project):
        obj = cls.objects.filter(leader=user, project=project, status=cls.__WAIT)
        count = obj.count()
        if count == 1:
            obj = obj.first()
            if obj.teams.count() != obj.project.groups_number + 1:
                raise ValueError(_("Vous n'ete pas un group suffisant"))
            obj.finished = timezone.now()
            obj.status = cls.__PROGRESS
            obj.invitations.clear()
            obj.save()
            return obj
        raise ValueError(_("Vous ne pouvez pas clore ce project"))

    @classmethod
    def retry(cls, user, project):
        obj = (
            cls.objects.filter(leader=user, project=project)
            .filter(~Q(status=cls.__WAIT))
            .order_by("-pk")
        )
        count = obj.count()
        if count:
            obj = obj.first()
            obj.invitations.clear()
            obj.status = cls.__FINISH
            obj.save()
            new = cls(project=project, leader=user)
            new.save()
            return new
        raise ValueError(_("Vous ne pouvez pas retry ce project"))

    @classmethod
    def register(cls, user, project):
        obj = cls.objects.filter(leader=user, project=project, status=cls.__PROGRESS)
        count = obj.count()
        if not count:
            new = cls(project=project, leader=user)
            new.save()
            return new
        raise ValueError(_("Vous ne pouvez pas vous enregistrer sur ce project"))

    def is_finish(self):
        return self.status == self.__FINISH

    def is_progress(self):
        return self.status == self.__PROGRESS

    def is_waiting(self):
        return self.status == self.__WAIT

    def is_corrected(self):
        return self.status == self.__CORRECT

    def is_fail(self):
        return False if self.scores >= 70 and self.is_finish else True

    def is_success(self):
        return True if self.scores >= 70 and self.is_finish else False

    def is_notyet(self):
        return False if self.is_finish else True

    @classmethod
    def extra(cls, user, project):
        return (
            cls.objects.filter(Q(leader=user) | Q(teams=user), project=project)
            .distinct()
            .aggregate(
                retry_nb=Count("pk", distinct=True),
                scores_max=Max("scores"),
                outstanding_nb=Count(
                    "evaluation", filter=Q(evaluation__outstanding=True), distinct=True,
                ),
            )
        )

project/forms.py
from .models import Project, ProjectRegister
from django.forms import ModelForm
from common.models import User


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = "__all__"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control"})


class ProjectRegisterForm(ModelForm):
    class Meta:
        model = ProjectRegister
        fields = ("teams", "invitations", "git")

    def __init__(self, **kwargs):
        creator = kwargs.pop("creator", None)
        super().__init__(**kwargs)
        self.fields["teams"].required = False
        self.fields["invitations"].required = False
        self.fields["git"].required = False
        self.fields["teams"].widget.attrs.update({"class": "form-control select2"})
        self.fields["invitations"].widget.attrs.update(
            {"class": "form-control select2"}
        )
        self.fields["git"].widget.attrs.update({"class": "form-control"})
        if creator:
            query = User.objects.exclude(id=creator.id)
            self.fields["teams"].queryset = query
            self.fields["invitations"].queryset = query

    def save(self, commit=True):
        if self.instance:
            self.instance.invitations.clear()
            self.instance.teams.clear()
        return super().save()

project/views.py
from django.views.generic import (
    ListView,
    DetailView,
    TemplateView,
    CreateView,
    UpdateView,
)
from common.mixins import IntraCeMixin
from .models import Project, ProjectRegister, Category, ProgLang
from django.db.models import Max, Q
from common.models import User
from .forms import ProjectForm, ProjectRegisterForm
from django.utils.translation import gettext as _
from django.contrib import messages
from django.http import HttpResponseRedirect


class ProjectList(IntraCeMixin, ListView):
    model = Project

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        visitor = User.objects.first()
        context["allcategory"] = Category.objects.all()
        context["allproglang"] = ProgLang.objects.all()
        query = (
            ProjectRegister.objects.filter(Q(leader=visitor) | Q(teams=visitor))
            .distinct()
            .values_list("project__pk")
        )
        context["projectregister_pk"] = [obj[0] for obj in query]
        return context


class ProjectDetail(IntraCeMixin, DetailView):
    model = Project
    register_template = "project/projectregister_detail.html"

    def access_fnc(self):
        obj = self.get_object()
        visitor = User.objects.first()
        if not obj:
            return False
        if (
            self.kwargs["register"]
            and not ProjectRegister.objects.filter(
                Q(leader=visitor) | Q(teams=visitor), project=obj,
            ).count()
        ):
            return False
        return True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        visitor = User.objects.first()
        context["register"] = ProjectRegister.objects.filter(
            Q(leader=visitor) | Q(teams=visitor), project=self.get_object()
        ).distinct()
        context["extra"] = ProjectRegister.extra(visitor, self.get_object())
        context["is_register"] = self.kwargs["register"]
        context["form_project"] = ProjectRegisterForm(
            instance=context["register"].first(),
            data=self.request.POST or None,
            creator=visitor,
        )
        return context

    def post(self, request, *args, **kwargs):
        visitor = User.objects.first()
        type_data = ("register", "close", "retry", "finish", "edit")
        project = Project.objects.get(id=kwargs["pk"])
        if "type" in request.POST and request.POST["type"] in type_data:
            try:
                obj = None
                if request.POST["type"] == "edit":
                    form = ProjectRegisterForm(instance=project, data=request.POST)
                    if not form.is_valid():
                        raise ValueError(form.errors)
                    form.save()
                    obj = project
                elif request.POST["type"] == "register":
                    obj = ProjectRegister.register(visitor, project)
                elif request.POST["type"] == "close":
                    obj = ProjectRegister.close(visitor, project)
                elif request.POST["type"] == "retry":
                    obj = ProjectRegister.retry(visitor, project)
                elif request.POST["type"] == "finish":
                    obj = ProjectRegister.finish(visitor, project)
                return HttpResponseRedirect(obj.get_absolute_url())
            except Exception as error:
                messages.error(self.request, error)
        else:
            messages.error(self.request, _("Mauvaise donner envoyer"))
        return self.get(self.request, *args, **kwargs)


class ProjectRegisterUpdateView(IntraCeMixin, UpdateView):
    model = ProjectRegister
    form_class = ProjectRegisterForm

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        visitor = User.objects.first()
        obj = self.get_object()
        if visitor == obj.leader and obj.is_waiting():
            return super().post(request, *args, **kwargs)
        messages.error(self.request, _("Vous ne pouvez pas modifier ce project"))
        return HttpResponseRedirect(obj.get_absolute_url())


class ProjectAdminListView(IntraCeMixin, ListView):
    model = Project
    template_name = "project/project_admin_list.html"

    def get_queryset(self):
        visitor = User.objects.first() or self.request.user
        return super().get_queryset().filter(creators=visitor)


class ProjectAdminCreateView(IntraCeMixin, CreateView):
    model = Project
    form_class = ProjectForm
    template_name = "project/project_admin_form.html"

    def post(self, request, *args, **kwargs):
        form = ProjectForm(data=request.POST)
        if form.is_valid():
            from_scoring = None
        return super().post(request, *args, **kwargs)

project/templates/project/widgets/feedback_list.html
{% comment %}
file for feedback by project
{% endcomment %}


{% load i18n utils tuser %}

<div class="card card-info card-outline">
    <div class="card-header">
        <h3 class="card-title">
            <i class="fas fa-comments mr-1"></i>
            {% trans "Feedback" %}
        </h3>
    </div>
    <div class="card-body p-0 text-center">
        {% for feed in wfeedbacks %}
        <div class="post">
            <div class="user-block">
                <img class="img-circle img-bordered-sm" src="{{feed.evaluator.user.photo|tc_photo}}" alt="user image">
                <span class="username">
                    <a href="{% url 'common:user-detail' feed.evaluator.pk %}">
                        {{feed.evaluator.get_full_name}}
                    </a>
                </span>
                <span class="description">{{feed.date|date:"d M - Y"}}</span>
            </div>
            <p>
                {{feed.comments}}
            </p>
            {% if feed.outstanding %}
            <span class="badge badge-warning">
                <i class="fa fa-star mr-1"></i>
                {% trans "Outstanding" %}
            </span>
            {% endif %}
        </div>
        {% empty %}
        <small class="text-muted">-- {% trans "Pas Devaluation" %} --</small>
        {% endfor %}
    </div>
</div>

project/templates/project/widgets/project_box.html
{% load i18n static utils tuser %}

<div class="{{col}}" data-type="projectbox" data-groups="{{wproject.is_group}}"
    data-experience="{{wproject.experience}}" data-name="{{wproject.name}}" data-propularity="0"
    data-date="{{wproject.date}}"
    data-projectuser="{% if wproject.pk in wproject_register_pk %}true{% else %}false{% endif %}" data-languges="
    {% for lang in wproject.languages.all %}
    {{lang.pk}}
    {% endfor %}
    " data-category="
    {% for cat in wproject.category.all %}
    {{cat.pk}}
    {% endfor %}
    ">
    <div class="small-box
            {% if wproject.scores %}
                bg-{{wproject.scores|color_project}}
            {% else %}
                bg-light
            {% endif %}">
        <div class="small-box bg-info">
            <div class="inner">
                <h3>
                    {{project}}
                    {% if wproject.scores %}
                    <span class="float-right badge {{wproject.scores|color_project}}">
                        {{wproject.scores}}
                    </span>
                    {% endif %}
                </h3>
                <p class="mt-4">
                    {% for user in wproject.users.all %}
                    <a href="{% url 'common:user-detail' user.pk %}">
                        <img class="img-circle w-10" src="{{user.photo|tc_photo}}" alt="User Image">
                    </a>
                    {% endfor %}
                </p>
            </div>
            <div class="icon">
                {% if wproject.scores >= 75%}
                <i class="fas fa-check"></i>
                {% elif wproject.scores %}
                <i class="fas fa-times mr-1"></i>
                {% else %}
                <i class="far fa-clock mr-1"></i>
                {% endif %}
            </div>
            {% for lang in wproject.languages.all %}
            <span class="badge bg-yellow">{{lang}}</span>
            {% endfor %}

            {% for cat in wproject.category.all %}
            <span class="badge bg-secondary">{{cat}}</span>
            {% endfor %}
            {% if wtype == 'register' %}
            <a href="{% url 'project:project-detail' project.project.pk %}" class="small-box-footer">
                {% elif wtype == 'project' %}
                <a href="{% url 'project:project-detail' wproject.pk %}" class="small-box-footer">
                    {% endif %}
                    {% trans "Plus d'info" %} <i class="fas fa-arrow-circle-right"></i>
                </a>
        </div>
    </div>
</div>

project/templates/project/widgets/project_comunity.html
{% load i18n static utils tuser %}


<div class="border-top mt-2 mb-2 text-center"></div>
<div class="row">
    <div class="col-lg-6">
        <h6>{% trans "Objectives" %}</h6>
        {% if wproject.objectives.count %}
        <blockquote class="quote-secondary">
            <p class="text-muted">
                {% for objective in wproject.objectives.all %}
                {{objective}}
                <br>
                {% endfor %}
            </p>
        </blockquote>
        {% endif %}
    </div>
    <div class="col-lg-6">
        <h6>{% trans "Skill" %}</h6>
        {% if wproject.skills.count %}
        <blockquote class="quote-secondary">
            <p class="text-muted">
                {% for skill in wproject.skills.all %}
                {{skill}}
                <br>
                {% endfor %}
            </p>
        </blockquote>
        {% endif %}
    </div>
</div>

<div class="border-top mt-2 mb-2 text-center"></div>
<h4>{% trans "Information Project" %}</h4>
<ul>
    {% with wproject.extra as wextra %}
    <li class="list-style-none">
        <i class="fa fa-project-diagram"></i>
        {{wextra.num}}
        {% trans "Project enregistrer" %}
    </li>
    <li class=" list-style-none">
        <i class="fa fa-trophy"></i>
        {{wextra.num_finish}}
        {% trans "Terminer" %}
    </li>
    <li class="list-style-none">
        <i class="fa fa-user"></i>
        {{wextra.num_student}}
        {% trans "Students currently doing this project" %}
    </li>
</ul>
<div class="border-top mt-2 mb-2 text-center"></div>
<div>
    <h4>
        <i class="fa fa-users-cog"></i>
        {% trans "Created by" %}
    </h4>
    <ul class="list-inline mt-2 ml-2">
        {% for wuser in wproject.creators.all %}
        <li class="list-inline-item">
            <a class="opacity-80" href="{% url 'common:user-detail' wuser.pk %}">
                <img class="mr-3 table-avatar img-size-64" src="{{wuser.photo|tc_photo}}" alt="User Image">
                <span class="users-list-name">
                    {{wuser.username}}
                </span>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
<div class="row">
    <div class="col-lg-6">
        <canvas class="chartjs" data-chart-fail="{{wextra.num_fail|add:0}}"
            data-chart-success="{{wextra.num_success|add:0}}" data-chart-notyet="{{wextra.num_notyet|add:1}}">
        </canvas>
    </div>
    <div class="col-lg-6"></div>
</div>
{% endwith %}

project/templates/project/widgets/team_list.html
{% load i18n utils tuser %}

<div class="card card-info">
    {% with wproject.teams.count as len %}
    <div class="card-header">
        <h3 class="card-title"><i class="fa fa-users mr-1"></i>{% trans "La Team" %}</h3>
        <div class="card-tools">
            <span class="badge badge-info">{{len|add:"1"}} {% trans "menbre" %}</span>
        </div>
    </div>
    <div class="card-body p-0">
        <ul class="list-inline mt-2 ml-2">
            <li class="list-inline-item">
                <img class="mr-3 table-avatar img-size-64" src="{{wproject.leader.photo|tc_photo}}" alt="User Image">
                <a class="users-list-name" href="{% url 'common:user-detail' wproject.leader.pk %}">
                    {{wproject.leader.username}}
                    <i class="fa fa-star text-warning"></i>
                </a>
            </li>
            {% for wuser in wproject.teams.all %}
            <li class="list-inline-item">
                <img class="mr-3 table-avatar img-size-64" src="{{wuser.photo|tc_photo}}" alt="User Image">
                <a class="users-list-name" href="#">{{wuser.username}}</a>
            </li>
            {% endfor %}

            {% if user == wproject.leader and wproject.is_waiting %}
            <li class="list-inline-item">
                <a class="opacity-50" data-target="#project_edit_team" data-toggle="modal" href="#">
                    <img class="mr-3 table-avatar img-size-64" src="{{None|tc_photo}}" alt="User Image">
                    <span class="users-list-name">
                        <i class="fa fa-plus"></i>
                        {% trans "Ajouter" %}
                    </span>
                </a>
            </li>
            <div class="modal fade" id="project_edit_team" style="display: none;" aria-hidden="true">
                <div class="modal-dialog hide">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">
                                {% trans "modification du groups" %}
                            </h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        <form method="post" action="{% url 'project:project-register-update' wlastproject.pk %}">
                            {% csrf_token %}
                            <div class="modal-body">
                                {{form_project.invitations.label_tag}}
                                {{form_project.invitations}}
                                <input type="hidden" name="type" value="edit">
                            </div>
                            <div class="modal-footer justify-content-between">
                                <button type="button" class="btn btn-outline-primary"
                                    data-dismiss="modal">{% trans "Close" %}</button>
                                <button type="submit" class="btn btn-primary api">
                                    {% trans "Save changes" %}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {% endif %}

        </ul>
        {% if wproject.invitations.count %}
        <div class="border-top mr-5 ml-5 text-center">
            <small class="text-muted">{% trans "En attente" %}</small>
        </div>
        <ul class="list-inline mt-2 ml-2">
            {% for wuser in wproject.invitations.all %}
            <li class="list-inline-item">
                <img class="mr-3 table-avatar img-size-64" src="{{wuser.photo|tc_photo}}" alt="User Image">
                <a class="users-list-name" href="#">{{wuser.username}}</a>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    {% endwith %}
</div>