_main_/urls.py
from django.contrib.staticfiles.urls import static

from django.contrib import admin
from django.urls import path, include, re_path
from _main_ import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("project/", include("project.urls", namespace="project")),
    path("api-auth/", include("rest_framework.urls")),
    path("api/", include("api.urls"), name="api"),
    path("", include("common.urls", namespace="common")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    if "debug_toolbar" in settings.INSTALLED_APPS:
        urlpatterns += [
            re_path(r"^__debug__/", include(debug_toolbar.urls)),
        ]

api/urls.py
from django.conf.urls import include
from rest_framework import routers
from django.urls import path
from api import views


router = routers.DefaultRouter()
router.register(
    "projectregister", views.ProjectRegisterViewSet, basename="projectregister"
)

urlpatterns = [
    path("", include((router.urls, "api"))),
]

common/urls.py
from django.urls import path
from .views import Accueil


app_name = "common"

urlpatterns = [
    path("accueil/", Accueil.as_view(), {"pk": None}, name="accueil"),
    path("user/<int:pk>/", Accueil.as_view(), name="user-detail"),
    path("", Accueil.as_view(), {"pk": None}),
]

project/urls.py
from django.urls import path
from .views import (
    ProjectList,
    ProjectDetail,
    ProjectAdminListView,
    ProjectAdminCreateView,
    ProjectRegisterUpdateView,
)

app_name = "project"

urlpatterns = [
    path("", ProjectList.as_view(), name="project-list"),
    path(
        "<int:pk>", ProjectDetail.as_view(), {"register": False}, name="project-detail"
    ),
    path(
        "register/<int:pk>",
        ProjectDetail.as_view(template_name="project/projectregister_detail.html"),
        {"register": True},
        name="project-register-detail",
    ),
    path(
        "register/update/<int:pk>",
        ProjectRegisterUpdateView.as_view(),
        name="project-register-update",
    ),
    path("admin/create", ProjectAdminCreateView.as_view(), name="project-create"),
    path("admin/", ProjectAdminListView.as_view(), name="project-tools"),
]

project/models/project.py
from django.db import models
from django.db.models import Count, Q
from django.urls import reverse
from django.utils import timezone
from common.manager import IntraCeQueryset


PROJECT_S = "project-resource/"
PROJECT_P = "project-pdf/"


class Project(models.Model):
    """
        models Projects
        one projects have many creator
    """

    name = models.CharField(max_length=50)
    description = models.TextField(null=True)
    creators = models.ManyToManyField("common.User")
    created = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=False)
    parent = models.ForeignKey(
        "project.Project", on_delete=models.SET_NULL, null=True, blank=True,
    )
    experience = models.PositiveIntegerField(default=50)
    corrector_number = models.PositiveSmallIntegerField(default=2)
    groups_number = models.PositiveSmallIntegerField(default=1)
    resource = models.FileField(
        upload_to=PROJECT_S, max_length=100, null=True, blank=True,
    )
    documentation = models.FileField(upload_to=PROJECT_P, max_length=100)
    videos = models.ManyToManyField("project.ProjectLink", blank=True)
    languages = models.ManyToManyField("project.ProgLang", blank=True)
    category = models.ManyToManyField("project.Category", blank=True)
    objectives = models.ManyToManyField("project.Objective", blank=True)
    skills = models.ManyToManyField("project.Skill", blank=True)
    objects = IntraCeQueryset.as_manager()

    def __str__(self):
        return self.name

    @property
    def is_group(self):
        return True if self.groups_number > 1 else False

    @classmethod
    def prefetch_std(cls):
        return ["creators", "videos", "languages", "category"]

    def get_absolute_url(self):
        return reverse("project:project-detail", kwargs={"pk": self.pk})

    def get_version(self):
        # aggregate version
        if hasattr(self, "ag_version"):
            return self.ag_version
        return self.projectversion_set.aggregate(Count("pk"))["pk"]

    def extra(self):
        extra = self.__class__.objects.aggregate(
            num=Count("projectregister__pk"),
            num_finish=Count(
                "projectregister__pk", filter=Q(projectregister__status="CLOSED")
            ),
            num_student=Count("projectregister__teams__pk")
            + Count("projectregister__leader__pk"),
            num_fail=Count(
                "projectregister__pk",
                filter=Q(
                    projectregister__status="FINISH", projectregister__scores__lt=70
                ),
            ),
            num_success=Count(
                "projectregister__pk",
                filter=Q(
                    projectregister__status="FINISH", projectregister__scores__gte=70
                ),
            ),
            num_notyet=Count(
                "projectregister__pk", filter=Q(projectregister__scores__isnull=True),
            ),
        )
        return extra

project/models/project_register.py
from django.db import models
from django.utils.translation import gettext as _
from common.manager import IntraCeQueryset
from django.utils import timezone
from django.db.models import Count, Max, Q
from django.urls import reverse


class ProjectRegister(models.Model):
    """
        models for project's user register
    """

    leader = models.ForeignKey(
        "common.User", on_delete=models.SET_NULL, related_name="leaders", null=True
    )
    teams = models.ManyToManyField("common.User", related_name="teams", blank=True)
    invitations = models.ManyToManyField(
        "common.User", related_name="invitations", blank=True
    )
    project = models.ForeignKey("project.Project", on_delete=models.CASCADE, null=False)

    """
        status qui gere le satus du project , 
        __WAIT = en attente de l'equipe ..ect
        __PROGRESS = en cours sur le project
        __FINISH = le project est clos , vous ne pouvez plus le modifier
    """
    __WAIT = "WAIT"
    __PROGRESS = "PROGRESS"
    __FINISH = "FINISH"
    __CORRECT = "CORRECTED"

    STATUS_CHOICES = (
        (__WAIT, _("En attente")),
        (__PROGRESS, _("En Cours")),
        (__FINISH, _("Terminer")),
    )
    status = models.CharField(
        max_length=8, choices=STATUS_CHOICES, default=__WAIT, blank=False
    )

    """
        date du debut et de fin du project
    """
    started = models.DateTimeField(auto_now_add=True, null=False)
    finished = models.DateTimeField(null=True, blank=True)

    git = models.URLField(max_length=200, blank=True, null=True)
    scores = models.IntegerField(blank=True, null=True, default=None)

    objects = IntraCeQueryset.as_manager()

    def __str__(self):
        return self.project.__str__()

    class Meta:
        ordering = ("-started",)

    @property
    def is_group(self):
        return self.project.is_group

    @classmethod
    def prefetch_std(cls):
        return ["user"]

    def start_or_end(self):
        return self.finished or self.started

    def get_absolute_url(self):
        return reverse(
            "project:project-register-detail", kwargs={"pk": self.project.pk}
        )

    @classmethod
    def finish(cls, user, project):
        obj = cls.objects.filter(leader=user, project=project, status=cls.__PROGRESS)
        count = obj.count()
        if count == 1:
            obj = obj.first()
            obj.finished = timezone.now()
            obj.status = cls.__FINISH
            obj.save()
            return obj
        raise ValueError(_("Vous ne pouvez pas terminer ce project"))

    @classmethod
    def close(cls, user, project):
        obj = cls.objects.filter(leader=user, project=project, status=cls.__WAIT)
        count = obj.count()
        if count == 1:
            obj = obj.first()
            if obj.teams.count() != obj.project.groups_number + 1:
                raise ValueError(_("Vous n'ete pas un group suffisant"))
            obj.finished = timezone.now()
            obj.status = cls.__PROGRESS
            obj.invitations.clear()
            obj.save()
            return obj
        raise ValueError(_("Vous ne pouvez pas clore ce project"))

    @classmethod
    def retry(cls, user, project):
        obj = (
            cls.objects.filter(leader=user, project=project)
            .filter(~Q(status=cls.__WAIT))
            .order_by("-pk")
        )
        count = obj.count()
        if count:
            obj = obj.first()
            obj.invitations.clear()
            obj.status = cls.__FINISH
            obj.save()
            new = cls(project=project, leader=user)
            new.save()
            return new
        raise ValueError(_("Vous ne pouvez pas retry ce project"))

    @classmethod
    def register(cls, user, project):
        obj = cls.objects.filter(leader=user, project=project, status=cls.__PROGRESS)
        count = obj.count()
        if not count:
            new = cls(project=project, leader=user)
            new.save()
            return new
        raise ValueError(_("Vous ne pouvez pas vous enregistrer sur ce project"))

    def is_finish(self):
        return self.status == self.__FINISH

    def is_progress(self):
        return self.status == self.__PROGRESS

    def is_waiting(self):
        return self.status == self.__WAIT

    def is_corrected(self):
        return self.status == self.__CORRECT

    def is_fail(self):
        return False if self.scores >= 70 and self.is_finish else True

    def is_success(self):
        return True if self.scores >= 70 and self.is_finish else False

    def is_notyet(self):
        return False if self.is_finish else True

    @classmethod
    def extra(cls, user, project):
        return (
            cls.objects.filter(Q(leader=user) | Q(teams=user), project=project)
            .distinct()
            .aggregate(
                retry_nb=Count("pk", distinct=True),
                scores_max=Max("scores"),
                outstanding_nb=Count(
                    "evaluation", filter=Q(evaluation__outstanding=True), distinct=True,
                ),
            )
        )

project/forms.py
from .models import Project, ProjectRegister
from django.forms import ModelForm
from common.models import User


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = "__all__"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control"})


class ProjectRegisterForm(ModelForm):
    class Meta:
        model = ProjectRegister
        fields = ("teams", "invitations", "git")

    def __init__(self, **kwargs):
        creator = kwargs.pop("creator", None)
        super().__init__(**kwargs)
        self.fields["teams"].required = False
        self.fields["invitations"].required = False
        self.fields["git"].required = False
        self.fields["teams"].widget.attrs.update({"class": "form-control select2"})
        self.fields["invitations"].widget.attrs.update(
            {"class": "form-control select2"}
        )
        self.fields["git"].widget.attrs.update({"class": "form-control"})
        if creator:
            query = User.objects.exclude(id=creator.id)
            self.fields["teams"].queryset = query
            self.fields["invitations"].queryset = query

    def save(self, commit=True):
        if self.instance:
            self.instance.invitations.clear()
            self.instance.teams.clear()
        return super().save()

project/views.py
from django.views.generic import (
    ListView,
    DetailView,
    TemplateView,
    CreateView,
    UpdateView,
)
from common.mixins import IntraCeMixin
from .models import Project, ProjectRegister, Category, ProgLang
from django.db.models import Max, Q
from common.models import User
from .forms import ProjectForm, ProjectRegisterForm
from django.utils.translation import gettext as _
from django.contrib import messages
from django.http import HttpResponseRedirect


class ProjectList(IntraCeMixin, ListView):
    model = Project

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        visitor = User.objects.first()
        context["allcategory"] = Category.objects.all()
        context["allproglang"] = ProgLang.objects.all()
        query = (
            ProjectRegister.objects.filter(Q(leader=visitor) | Q(teams=visitor))
            .distinct()
            .values_list("project__pk")
        )
        context["projectregister_pk"] = [obj[0] for obj in query]
        return context


class ProjectDetail(IntraCeMixin, DetailView):
    model = Project
    register_template = "project/projectregister_detail.html"

    def access_fnc(self):
        obj = self.get_object()
        visitor = User.objects.first()
        if not obj:
            return False
        if (
            self.kwargs["register"]
            and not ProjectRegister.objects.filter(
                Q(leader=visitor) | Q(teams=visitor), project=obj,
            ).count()
        ):
            return False
        return True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        visitor = User.objects.first()
        context["register"] = ProjectRegister.objects.filter(
            Q(leader=visitor) | Q(teams=visitor), project=self.get_object()
        ).distinct()
        context["extra"] = ProjectRegister.extra(visitor, self.get_object())
        context["is_register"] = self.kwargs["register"]
        context["form_project"] = ProjectRegisterForm(
            instance=context["register"].first(),
            data=self.request.POST or None,
            creator=visitor,
        )
        return context

    def post(self, request, *args, **kwargs):
        visitor = User.objects.first()
        type_data = ("register", "close", "retry", "finish", "edit")
        project = Project.objects.get(id=kwargs["pk"])
        if "type" in request.POST and request.POST["type"] in type_data:
            try:
                obj = None
                if request.POST["type"] == "edit":
                    form = ProjectRegisterForm(instance=project, data=request.POST)
                    if not form.is_valid():
                        raise ValueError(form.errors)
                    form.save()
                    obj = project
                elif request.POST["type"] == "register":
                    obj = ProjectRegister.register(visitor, project)
                elif request.POST["type"] == "close":
                    obj = ProjectRegister.close(visitor, project)
                elif request.POST["type"] == "retry":
                    obj = ProjectRegister.retry(visitor, project)
                elif request.POST["type"] == "finish":
                    obj = ProjectRegister.finish(visitor, project)
                return HttpResponseRedirect(obj.get_absolute_url())
            except Exception as error:
                messages.error(self.request, error)
        else:
            messages.error(self.request, _("Mauvaise donner envoyer"))
        return self.get(self.request, *args, **kwargs)


class ProjectRegisterUpdateView(IntraCeMixin, UpdateView):
    model = ProjectRegister
    form_class = ProjectRegisterForm

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        visitor = User.objects.first()
        obj = self.get_object()
        if visitor == obj.leader and obj.is_waiting():
            return super().post(request, *args, **kwargs)
        messages.error(self.request, _("Vous ne pouvez pas modifier ce project"))
        return HttpResponseRedirect(obj.get_absolute_url())


class ProjectAdminListView(IntraCeMixin, ListView):
    model = Project
    template_name = "project/project_admin_list.html"

    def get_queryset(self):
        visitor = User.objects.first() or self.request.user
        return super().get_queryset().filter(creators=visitor)


class ProjectAdminCreateView(IntraCeMixin, CreateView):
    model = Project
    form_class = ProjectForm
    template_name = "project/project_admin_form.html"

    def post(self, request, *args, **kwargs):
        form = ProjectForm(data=request.POST)
        if form.is_valid():
            from_scoring = None
        return super().post(request, *args, **kwargs)

project/templates/project/project_admin_detail.html
{% extends 'base.html' %}

project/templates/project/project_admin_form.html
{% extends 'base.html' %}
{% load i18n widget_tweaks %}

{% block contents %}


<div class="card card-primary card-outline card-tabs">
    <div class="card-header p-0 pt-1 border-bottom-0">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#project">{% trans "project" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#correction">{% trans "correction" %}</a>
            </li>
        </ul>
        <div class="card-body">
            <div class="tab-content">
                <div class="tab-pane active" id="project" role="tabpanel" aria-labelledby="custom-tabs-two-home-tab">      
                    <h2>{% trans "Porject creation" %}</h2>
                    <form method="post" enctype="multipart/form-data">{% csrf_token %}
                        {{form}}
                        <button class="btn btn-primary mt-2" type="submit">
                            <i class="fa fa-plus"> {% trans "Ajouter" %}</i>
                        </button>
                    </form>
                </div>
                <div class="tab-pane fade" id="correction" role="tabpanel" aria-labelledby="custom-tabs-two-home-tab">
                    <h2>{% trans "Porject corrections" %}</h2>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock contents %}

project/templates/project/project_admin_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block contents %}
<a class="btn btn-primary" href="{% url 'project:project-create' %}">
    <i class="fa fa-plus"> {% trans "Ajouter" %}</i>
</a>
{% endblock contents %}

project/templates/project/project_detail.html
{% extends 'base.html' %}
{% load i18n static %}

{% block style_extra %}
<link srel="stylesheet" href="{% static 'admin-lte/plugins/chart.js/Chart.min.css' %}">
{% endblock style_extra %}

{% block contents %}

<div class="row mt-1">
    <div class="col-12">
        {% include 'project/widgets/project_info.html' with wproject=object wlastproject=register.first wtype='long' %}
    </div>
</div>

{% endblock contents %}
{% block js_extra %}
<script src="{% static 'admin-lte/plugins/chart.js/Chart.min.js' %}"></script>
{% endblock js_extra %}

project/templates/project/project_list.html
{% extends 'base.html' %}
{% load i18n static utils tuser %}

{% block breadcrumb%}
{% endblock breadcrumb%}


{% block contents %}
<div class="row mt-1">
    <div class="col-md-3">
        {% include 'project/tools/project_filter.html' %}
    </div>
    <div class="col-9">
        <div class="row">
            {% for project in object_list %}
            {% include 'project/widgets/project_box.html' with wproject=project col="col-lg-3" wtype="project" wproject_register_pk=projectregister_pk%}
            {% endfor %}
        </div>
    </div>
    {% endblock contents %}

    {% block js_extra %}
    <script src="{% static 'js/project_filter.js' %}"></script>
    {% endblock js_extra %}

project/templates/project/projectregister_detail.html
{% extends 'base.html' %}
{% load i18n utils tuser %}

{% block breadcrumb%}
{% endblock breadcrumb%}


{% block contents %}

<div class="row mt-1">
    <div class="col-md-12">
        {% include 'project/widgets/project_info.html' with wproject=object wlastproject=register.first wtype="small" %}
    </div>
</div>


{% endblock contents %}

project/templates/project/projectregister_list.html
{% extends 'base.html' %}
{% load i18n utils tuser %}

{% block breadcrumb%}
{% endblock breadcrumb%}


{% block contents %}
<div class="row mt-1">
    {% for project in allproject %}
    <div class="col-lg-3">
        <div class="small-box
        {% if project.scores %} bg-{{project.scores|color_project}} {% else %} bg-light {% endif %}">
            <div class="small-box bg-info">
                <div class="inner">
                    <h3>
                        {{project}}
                        {% if project.scores %}
                        <span class="float-right badge {{project.scores|color_project}}">
                            {{project.scores}}
                        </span>
                        {% endif %}
                    </h3>
                    <p class="mt-4">
                        {% for user in project.users.all %}
                        <a href="{% url 'common:user-detail' user.pk %}">
                            <img class="img-circle w-10" src="{{user.photo|tc_photo}}" alt="User Image">
                        </a>
                        {% endfor %}
                    </p>
                </div>
                <div class="icon">
                    {% if project.scores >= 75%}
                    <i class="fas fa-check"></i>
                    {% elif project.scores %}
                    <i class="fas fa-times mr-1"></i>
                    {% else %}
                    <i class="far fa-clock mr-1"></i>
                    {% endif %}
                </div>
                <a href="{% url 'project:project-detail' project.project.pk %}" class="small-box-footer">
                    {% trans "Plus d'info" %} <i class="fas fa-arrow-circle-right"></i>
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock contents %}