_main_/urls.py
from django.contrib.staticfiles.urls import static

from django.contrib import admin
from django.urls import path, include, re_path
from _main_ import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("project/", include("project.urls", namespace="project")),
    path("api-auth/", include("rest_framework.urls")),
    path("api/", include("api.urls"), name="api"),
    path("", include("common.urls", namespace="common")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    if "debug_toolbar" in settings.INSTALLED_APPS:
        urlpatterns += [
            re_path(r"^__debug__/", include(debug_toolbar.urls)),
        ]

api/urls.py
from django.conf.urls import include
from rest_framework import routers
from django.urls import path
from api import views


router = routers.DefaultRouter()
router.register(
    "projectregister", views.ProjectRegisterViewSet, basename="projectregister"
)

urlpatterns = [
    path("", include((router.urls, "api"))),
]

common/urls.py
from django.urls import path
from .views import Accueil


app_name = "common"

urlpatterns = [
    path("accueil/", Accueil.as_view(), {"pk": None}, name="accueil"),
    path("user/<int:pk>/", Accueil.as_view(), name="user-detail"),
    path("", Accueil.as_view(), {"pk": None}),
]

project/urls.py
from django.urls import path
from .views import (
    ProjectList,
    ProjectDetail,
    ProjectAdminListView,
    ProjectAdminCreateView,
    ProjectRegisterUpdateView,
)

app_name = "project"

urlpatterns = [
    path("", ProjectList.as_view(), name="project-list"),
    path(
        "<int:pk>", ProjectDetail.as_view(), {"register": False}, name="project-detail"
    ),
    path(
        "register/<int:pk>",
        ProjectDetail.as_view(template_name="project/projectregister_detail.html"),
        {"register": True},
        name="project-register-detail",
    ),
    path(
        "register/update/<int:pk>",
        ProjectRegisterUpdateView.as_view(),
        name="project-register-update",
    ),
    path("admin/create", ProjectAdminCreateView.as_view(), name="project-create"),
    path("admin/", ProjectAdminListView.as_view(), name="project-tools"),
]

templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}" />
    <title>{% block title %}{% endblock title %}</title>
    {% block head %}{% endblock head %}

    {# ----------------- modules node  CSS ----------------- #}
    {% block style_extra %}{% endblock style_extra %}
    <link rel="stylesheet" href="{% static '/admin-lte/dist/css/adminlte.min.css' %}">
    <link rel="stylesheet" href="{% static '/admin-lte/plugins/jquery-ui/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static '/admin-lte/plugins/fontawesome-free/css/all.css' %}">
    <link rel="stylesheet" href="{% static '/admin-lte/plugins/sweetalert2/sweetalert2.min.css' %}">
    <link rel="stylesheet" href="{% static '/admin-lte/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' %}">
    <link rel="stylesheet" href="{% static '/admin-lte/plugins/toastr/toastr.min.css' %}">
    <link rel="stylesheet" href="{% static '/admin-lte/plugins/select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static '/admin-lte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <script src="{% static '/vue/dist/vue.js' %}"></script>
    {# ----------------- modules node  JS ----------------- #}
    <script src="{% static '/admin-lte/plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static '/admin-lte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static '/admin-lte/plugins/select2/js/select2.min.js' %}"></script>
    <script src="{% static '/admin-lte/dist/js/adminlte.min.js' %}"></script>
    <script src="{% static '/admin-lte/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/admin-lte/plugins/sweetalert2/sweetalert2.all.min.js' %}"></script>
    <script src="{% static '/admin-lte/plugins/toastr/toastr.min.js' %}"></script>

</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        {% include 'navbar.html' %}
        {% include 'sidebar.html' %}
        <div class="content-wrapper">
            <section class="content">
                <div class="container-fluid">
                    {% block breadcrumb %}
                    <div class="content-header">
                        <div class="container-fluid">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h1 class="m-0 text-dark">
                                        {% block breadcrumb_title %}{% endblock breadcrumb_title %}</h1>
                                </div>
                                <div class="col-sm-6">
                                    <ol class="breadcrumb float-sm-right">
                                        {% block breadcrumb_sub %}{% endblock breadcrumb_sub %}
                                    </ol>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endblock breadcrumb %}
                    {# ----------------- content ----------------- #}
                    {% block contents %}
                    {% endblock contents %}
                </div>
            </section>
        </div>
    </div>
    {# ----------------- footer ----------------- #}
    {% include 'footer.html' %}

    {# ----------------- notification ----------------- #}
    {% include 'utility/notification.html' %}

</body>

<script>
    console.log('iciciic')
</script>
<script src="{% static '/js/common.js' %}"></script>

{# ----------------- js extra ----------------- #}
{% block js_extra %}
{% endblock js_extra %}

</html>

templates/footer.html
{% load static %}
<!-- /.content-wrapper -->
<footer class="main-footer">
    <strong>Rgermain &copy; 2019-2020 <a href="https://framagit.org/rgermain/intra42-ce">Intra42 Community
            Edition</a>.</strong>
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> {{git.version}}
    </div>
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    {% for invitation in invitations %}

    {% endfor %}
</aside>

templates/header.html
{% load static %}

<div class="col-1">
    <div class="container-fluid">
        <div class="text-center">
            <a class="navbar-brand" href="#">
                <img src="{{MEDIA}}{% static 'img/logo.png' %}" class="img-fluid text-center" width="50" height="50"
                    alt="">
            </a>
        </div>
    </div>
</div>
<div class="col-11">
    <nav class="navbar navbar-expand-lg navbar-light bg-light w-auto">
        <form class="form-inline">
            <button class="btn" type="submit"><em class="fa fa-search"></em></button>
            <input class="form-control" type="search" placeholder="Search" aria-label="Search">
        </form>
    </nav>
</div>

templates/navbar.html
{% load tuser i18n %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">{{notifications|length}}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                {% for notfication in notifications %}
                {% include 'utility/notif.html' with wnotif=notfication %}
                {% endfor %}
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>



        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>



</nav>
<!-- /.navbar -->


{% for i in notifications %}
<div class="modal" id="notif{{forloop.count}}" style="display: none;" aria-hidden="true">
    <div class="modal-dialog hide">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">
                    {% trans "Invitations a un project" %}
                </h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            {% csrf_token %}
            <div class="modal-body">
                <div class="input-group">
                    <form method="post" action="">
                        <input type="hidden" name="invitations" value="true">
                        <button type="submit" class="btn btn-primary api">
                            {% trans "accepter" %}
                        </button>
                    </form>
                    <form method="post" action="">
                        <input type="hidden" name="invitations" value="false">
                        <button type="submit" class="btn btn-primary api">
                            {% trans "refuser" %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
        <div class="modal-footer justify-content-between">
            <button type="button" class="btn btn-outline-primary" data-dismiss="modal">{% trans "Close" %}</button>
        </div>
    </div>
</div>
{% endfor %}
{% block js_extra %}
<script>
</script>
{% endblock js_extra %}

templates/sidebar.html
{% load static tuser i18n %}
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'common:accueil' %}" class="brand-link bg-light">
        <img src="{% static 'img/logo.png' %}" alt="Intra42-CE Logo" class="brand-image img-circle" style="opacity: .8">
        <span class="brand-text font-weight-light">Intra42-CE</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{user.photo|tc_photo}}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="{% url 'common:user-detail' user.pk %}" class="d-block">{{user.username|title}}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            {% blocktrans %} Project register {% endblocktrans %}
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    {% comment %} -- list of current project -- {% endcomment %}
                    <ul class="nav nav-treeview">
                        {% for project in currentproject %}
                        <li class="nav-item">
                            <a href="{% url 'project:project-register-detail' project.project.pk %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{project}}</p>
                            </a>
                        </li>
                        {% empty %}
                        <li class="nav-item text-center">
                            <p class="text-secondary"> -- {% blocktrans %} nothing register {% endblocktrans %} -- </p>
                        </li>
                        {% endfor %}
                    </ul>
                </li>

                {% comment %} -- link general -- {% endcomment %}
                <li class="nav-header">{% trans "general"|upper %}</li>
                <li class="nav-item">
                    <a href="{% url 'project:project-list' %}" class="nav-link">
                        <i class="nav-icon fas fa-project-diagram"></i>
                        <p>
                            {% trans "Project" %}
                            {% if has_new_project %}
                            <span class=" right badge badge-danger">New</span>
                            {% endif %}
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'project:project-list' %}" class="nav-link">
                        <i class="nav-icon fas fa-video"></i>
                        <p>
                            {% trans "Video" %}
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'project:project-list' %}" class="nav-link">
                        <i class="nav-icon fas fa-file"></i>
                        <p>
                            {% trans "Documentation" %}
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'project:project-tools' %}" class="nav-link">
                        <i class="nav-icon fas fa-tools"></i>
                        <p>
                            {% trans "administration" %}
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>